name: Ruby
on: [push, pull_request]
jobs:
  specs:
    strategy:
      matrix:
        ruby-version: ['2.4', '2.7', '3.0']

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache:
      - run: bundle exec rake
